# Code Samples From Large Group

Place your notes and code samples from large group here.

In [1]:
import pandas as pd 
import numpy as np

In [2]:
names = pd.Series(data=["Art", "Bette", "Chris"], name="first_name")

In [3]:
names

0      Art
1    Bette
2    Chris
Name: first_name, dtype: object

In [4]:
grades = pd.Series(data=[100, 100, 75], name="grades")
grades

0    100
1    100
2     75
Name: grades, dtype: int64

In [6]:
students = pd.DataFrame({ "name":names, "grade": grades})
students

    name  grade
0    Art    100
1  Bette    100
2  Chris     75

In [7]:
data = [
    {"name": "Bob", "state": "NY", "years": 15},
    {"name": "Tad", "state": "NY"},
    {"name": "Kelly", "state": "PA", "years": 25},
    {"name": "Shelly", "state": "PA", "years": 5}
]

In [8]:
df = pd.DataFrame(data)

In [9]:
df

     name state  years
0     Bob    NY   15.0
1     Tad    NY    NaN
2   Kelly    PA   25.0
3  Shelly    PA    5.0

In [10]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4 entries, 0 to 3
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   name    4 non-null      object
 1   state   4 non-null      object
 2   years   3 non-null      float64
dtypes: float64(1), object(2)
memory usage: 228.0+ bytes

In [11]:
df.columns

Index(['name', 'state', 'years'], dtype='object')

In [12]:
for col in df.columns:
    print(col)

name
state
years

In [13]:
df.columns = [ "senator_name", "senator_state", "senator_years"]

In [14]:
df

  senator_name senator_state  senator_years
0          Bob            NY           15.0
1          Tad            NY            NaN
2        Kelly            PA           25.0
3       Shelly            PA            5.0

In [15]:
data

[{'name': 'Bob', 'state': 'NY', 'years': 15},
 {'name': 'Tad', 'state': 'NY'},
 {'name': 'Kelly', 'state': 'PA', 'years': 25},
 {'name': 'Shelly', 'state': 'PA', 'years': 5}]

In [16]:
type(df)

pandas.core.frame.DataFrame

In [17]:
print(df)

  senator_name senator_state  senator_years
0          Bob            NY           15.0
1          Tad            NY            NaN
2        Kelly            PA           25.0
3       Shelly            PA            5.0

In [18]:
df

  senator_name senator_state  senator_years
0          Bob            NY           15.0
1          Tad            NY            NaN
2        Kelly            PA           25.0
3       Shelly            PA            5.0

In [19]:
from IPython.display import display

display(df)
display(df)

  senator_name senator_state  senator_years
0          Bob            NY           15.0
1          Tad            NY            NaN
2        Kelly            PA           25.0
3       Shelly            PA            5.0

  senator_name senator_state  senator_years
0          Bob            NY           15.0
1          Tad            NY            NaN
2        Kelly            PA           25.0
3       Shelly            PA            5.0

In [20]:
df

  senator_name senator_state  senator_years
0          Bob            NY           15.0
1          Tad            NY            NaN
2        Kelly            PA           25.0
3       Shelly            PA            5.0

In [21]:
df2 = df[["senator_name", "senator_state"]]

In [22]:
df2

  senator_name senator_state
0          Bob            NY
1          Tad            NY
2        Kelly            PA
3       Shelly            PA

In [23]:
df3 = df[df['senator_state'] == 'NY']

In [24]:
df3

  senator_name senator_state  senator_years
0          Bob            NY           15.0
1          Tad            NY            NaN

In [25]:
df

  senator_name senator_state  senator_years
0          Bob            NY           15.0
1          Tad            NY            NaN
2        Kelly            PA           25.0
3       Shelly            PA            5.0

In [27]:
df[ df['senator_state'] =='PA'][['senator_name']]

  senator_name
2        Kelly
3       Shelly

In [28]:
something = df.loc[2, "senator_name"]
print(something)

Kelly

In [29]:
df

  senator_name senator_state  senator_years
0          Bob            NY           15.0
1          Tad            NY            NaN
2        Kelly            PA           25.0
3       Shelly            PA            5.0

In [30]:
df["senator_name"]

0       Bob
1       Tad
2     Kelly
3    Shelly
Name: senator_name, dtype: object

In [31]:
df['senator_state'].unique()

array(['NY', 'PA'], dtype=object)

In [32]:
df['senator_state'].value_counts()

senator_state
NY    2
PA    2
Name: count, dtype: int64

In [ ]:
df[["senator_name"]]

In [33]:
type(df["senator_state"])

pandas.core.series.Series

In [34]:
dedupe_states = sorted(list(df["senator_state"].unique()))
dedupe_states

['NY', 'PA']

In [35]:
df["senator_state"].unique()

array(['NY', 'PA'], dtype=object)

In [36]:
file = "https://raw.githubusercontent.com/mafudge/datasets/master/superhero/superhero-movie-dataset-1978-2012-header.csv"
df = pd.read_csv(file, header=0, sep=",")

In [37]:
df

,Year,Title,Comic,IMDB Score,RT Score,Composite Score,Opening Weekend Box Office,Avg Ticket Price,Opening Weekend Attendance,US Population That Year
0,1978,Superman,DC,7.3,95,84.0,7465343.0,2.34,3.190318e+06,222584545
1,1980,Superman II,DC,6.7,88,77.5,14100523.0,2.69,5.241830e+06,227224681
2,1982,Swamp Thing,DC,5.3,60,56.5,NaN,2.94,NaN,231664458
3,1983,Superman III,DC,4.9,24,36.5,13352357.0,3.15,4.238843e+06,233791994
4,1984,Supergirl,DC,4.2,8,25.0,5738249.0,3.36,1.707812e+06,235824902
5,1986,Howard the Duck,Marvel,4.3,16,29.5,5070136.0,3.71,1.366613e+06,240132887
6,1987,Superman IV: The Quest for Peace,DC,3.6,10,23.0,5683122.0,3.91,1.453484e+06,242288918
7,1989,Batman,DC,7.6,71,73.5,40489746.0,3.97,1.019893e+07,246819230
8,1989,The Return of Swamp Thing,DC,3.9,40,39.5,NaN,3.97,NaN,246819230
9,1989,The Punisher,Marvel,5.4,24,39.0,NaN,3.97,NaN,246819230
10,1992,Batman Returns,DC,7.0,78,74.0,45687711.0,4.15,1.100909e+07,255029699
11,1995,Batman Forever,DC,5.4,42,48.0,52784433.0,4.35,1.213435e+07,262803276
12,1997,Batman & Robin,DC,3.6,12,24.0,42872605.0,4.59,9.340437e+06,267783607
13,1997,Steel,DC,2.7,12,19.5,870068.0,4.59,1.895573e+05,267783607
14,1998,Blade,Marvel,7.0,55,62.5,17073856.0,4.69,3.640481e+06,270248003
15,2000,X-Men,Marvel,7.4,82,78.0,54471475.0,5.39,1.010603e+07,282171957
16,2002,Blade II,Marvel,6.6,59,62.5,32528016.0,5.81,5.598626e+06,287803914
17,2002,Spider-Man,Marvel,7.4,89,81.5,114844116.0,5.81,1.976663e+07,287803914
18,2003,Daredevil,Marvel,5.4,45,49.5,40310419.0,6.03,6.684978e+06,290326418
19,2003,Hulk,Marvel,5.7,62,59.5,62128420.0,6.03,1.030322e+07,290326418
20,2003,X2,Marvel,7.6,88,82.0,85558731.0,6.03,1.418884e+07,290326418
21,2004,Blade: Trinity,Marvel,5.8,26,42.0,16061271.0,6.21,2.586356e+06,293045739
22,2004,Catwoman,DC,3.2,10,21.0,16728411.0,6.21,2.693786e+06,293045739
23,2004,Spider-Man 2,Marvel,7.5,93,84.0,88156227.0,6.21,1.419585e+07,293045739
24,2004,The Punisher,Marvel,6.4,29,46.5,13834527.0,6.21,2.227782e+06,293045739
25,2005,Batman Begins,DC,8.3,85,84.0,48745440.0,6.41,7.604593e+06,295753151
26,2005,Elektra,Marvel,4.8,10,29.0,12804793.0,6.41,1.997628e+06,295753151
27,2005,Fantastic Four,Marvel,5.7,27,42.0,56061504.0,6.41,8.745944e+06,295753151
28,2006,Superman Returns,DC,6.3,76,69.5,52535096.0,6.55,8.020625e+06,298593212
29,2006,X-Men: The Last Stand,Marvel,6.8,57,62.5,102750665.0,6.55,1.568712e+07,298593212
30,2007,Fantastic Four: Rise of the Silver Surfer,Marvel,5.7,37,47.0,58051684.0,6.88,8.437745e+06,301579895
31,2007,Ghost Rider,Marvel,5.2,26,39.0,45388836.0,6.88,6.597215e+06,301579895
32,2007,Spider-Man 3,Marvel,6.3,63,63.0,151116516.0,6.88,2.196461e+07,301579895
33,2008,The Dark Knight,DC,8.9,94,91.5,158411483.0,7.18,2.206288e+07,304374846
34,2008,The Incredible Hulk,Marvel,7.0,67,68.5,55414050.0,7.18,7.717834e+06,304374846
35,2008,Iron Man,Marvel,7.9,94,86.5,98618668.0,7.18,1.373519e+07,304374846
36,2008,Punisher: War Zone,Marvel,6.0,26,43.0,4271451.0,7.18,5.949096e+05,304374846
37,2009,Watchmen,DC,7.7,64,70.5,55214334.0,7.50,7.361911e+06,307006550
38,2009,X-Men Origins: Wolverine,Marvel,6.7,37,52.0,85058003.0,7.50,1.134107e+07,307006550
39,2010,Iron Man 2,Marvel,7.1,74,72.5,128122480.0,7.89,1.623859e+07,308745538
40,2010,Jonah Hex,DC,4.6,13,29.5,5379365.0,7.89,6.817953e+05,308745538
41,2011,Captain America: The First Avenger,Marvel,6.8,79,73.5,65058524.0,7.93,8.204101e+06,311591917
42,2011,Green Lantern,DC,5.9,27,43.0,53174303.0,7.93,6.705461e+06,311591917
43,2011,Thor,Marvel,7.0,77,73.5,65723338.0,7.93,8.287937e+06,311591917
44,2011,X-Men: First Class,Marvel,7.9,87,83.0,55101604.0,7.93,6.948500e+06,311591917
45,2012,Marvel's The Avengers,Marvel,8.7,92,89.5,207438708.0,7.92,2.619176e+07,314055984
46,2012,The Dark Knight Rises,DC,9.1,86,88.5,160887295.0,7.92,2.031405e+07,314055984
47,2012,Ghost Rider: Spirit of Vengeance,Marvel,4.5,17,31.0,22115334.0,7.92,2.792340e+06,314055984
48,2012,The Amazing Spider-Man,Marvel,7.6,74,75.0,62004688.0,7.92,7.828875e+06,314055984

In [40]:
students = pd.read_csv(
    "https://raw.githubusercontent.com/mafudge/datasets/master/delimited/students-header.psv",
    sep="|"
)

In [41]:
students

     Name  Grade       Year
0    Abby    7.0   Freshman
1     Bob    9.0  Sophomore
2   Chris   10.0     Senior
3    Dave    8.0   Freshman
4   Ellen    7.0  Sophomore
5    Fran   10.0     Senior
6    Greg    8.0   Freshman
7   Helen    NaN  Sophomore
8    Iris   10.0     Senior
9   Jimmy    8.0   Freshman
10  Karen    7.5   Freshman
11  Lynne   10.0  Sophomore
12   Mike   10.0  Sophomore
13   Nico    NaN     Junior
14   Pete    8.0   Freshman

In [ ]:
df.info()

In [ ]:
df.describe()

In [ ]:
df.head(n=7)

In [ ]:
df.tail(n=3)

In [ ]:
df['Comic'].value_counts()

In [ ]:
df['Year'].value_counts()

In [ ]:
df2000 = df[df['Year'] >= 2000]

In [ ]:
df2000['Comic'].value_counts()

In [ ]:
df.dropna()

In [ ]:
df.to_csv("super.csv")

In [42]:
students

     Name  Grade       Year
0    Abby    7.0   Freshman
1     Bob    9.0  Sophomore
2   Chris   10.0     Senior
3    Dave    8.0   Freshman
4   Ellen    7.0  Sophomore
5    Fran   10.0     Senior
6    Greg    8.0   Freshman
7   Helen    NaN  Sophomore
8    Iris   10.0     Senior
9   Jimmy    8.0   Freshman
10  Karen    7.5   Freshman
11  Lynne   10.0  Sophomore
12   Mike   10.0  Sophomore
13   Nico    NaN     Junior
14   Pete    8.0   Freshman

In [43]:
# first I need to know what columns
students.columns

Index(['Name', 'Grade', 'Year'], dtype='object')

In [44]:
# this gets the unique counts by year
students['Year'].value_counts()

Year
Freshman     6
Sophomore    5
Senior       3
Junior       1
Name: count, dtype: int64

In [45]:
#I wonder who that jr. is?
students[ students['Year'] == 'Junior' ]

    Name  Grade    Year
13  Nico    NaN  Junior

In [46]:
# distribution of grade
students['Grade'].value_counts()

Grade
10.0    5
8.0     4
7.0     2
9.0     1
7.5     1
Name: count, dtype: int64

In [47]:
students[ students["Grade"] >= 9.0 ]

     Name  Grade       Year
1     Bob    9.0  Sophomore
2   Chris   10.0     Senior
5    Fran   10.0     Senior
8    Iris   10.0     Senior
11  Lynne   10.0  Sophomore
12   Mike   10.0  Sophomore

In [50]:
# save in a variable
high_achievers = students[ students["Grade"] >= 9.0 ]
high_achievers.to_excel("high-achievers.xlsx", index=False)

In [51]:
bench = pd.read_excel("BenchmarkTests.xls")
bench

        IBM SATA SAN        \\128.230.182.202\BenchmarkTest\
0      Seneca 1U HDD  \\ist-s-archive1.ad.syr.edu\Benchmark\
1  Dell R200 - ITELL              \\128.230.38.57\Benchmark\
2   Dell 775N - IMG1  \\ist-s-img1.ad.syr.edu\BenchmarkTest\
3           G: Drive                                     NaN

In [55]:
file = "https://raw.githubusercontent.com/mafudge/datasets/master/superhero/superhero-movie-dataset-1978-2012-header.csv"
sh = pd.read_csv(file, header=0, sep=",")
sh.head(n=4)

,Year,Title,Comic,IMDB Score,RT Score,Composite Score,Opening Weekend Box Office,Avg Ticket Price,Opening Weekend Attendance,US Population That Year
0,1978,Superman,DC,7.3,95,84.0,7465343.0,2.34,3190317.521,222584545
1,1980,Superman II,DC,6.7,88,77.5,14100523.0,2.69,5241830.112,227224681
2,1982,Swamp Thing,DC,5.3,60,56.5,NaN,2.94,NaN,231664458
3,1983,Superman III,DC,4.9,24,36.5,13352357.0,3.15,4238843.492,233791994

In [56]:
# first 3
sh.head(n=3)

,Year,Title,Comic,IMDB Score,RT Score,Composite Score,Opening Weekend Box Office,Avg Ticket Price,Opening Weekend Attendance,US Population That Year
0,1978,Superman,DC,7.3,95,84.0,7465343.0,2.34,3190317.521,222584545
1,1980,Superman II,DC,6.7,88,77.5,14100523.0,2.69,5241830.112,227224681
2,1982,Swamp Thing,DC,5.3,60,56.5,NaN,2.94,NaN,231664458

In [58]:
sh.tail(n=5)

,Year,Title,Comic,IMDB Score,RT Score,Composite Score,Opening Weekend Box Office,Avg Ticket Price,Opening Weekend Attendance,US Population That Year
44,2011,X-Men: First Class,Marvel,7.9,87,83.0,55101604.0,7.93,6.948500e+06,311591917
45,2012,Marvel's The Avengers,Marvel,8.7,92,89.5,207438708.0,7.92,2.619176e+07,314055984
46,2012,The Dark Knight Rises,DC,9.1,86,88.5,160887295.0,7.92,2.031405e+07,314055984
47,2012,Ghost Rider: Spirit of Vengeance,Marvel,4.5,17,31.0,22115334.0,7.92,2.792340e+06,314055984
48,2012,The Amazing Spider-Man,Marvel,7.6,74,75.0,62004688.0,7.92,7.828875e+06,314055984

In [76]:
sh.sample(n=5)

,Year,Title,Comic,IMDB Score,RT Score,Composite Score,Opening Weekend Box Office,Avg Ticket Price,Opening Weekend Attendance,US Population That Year
41,2011,Captain America: The First Avenger,Marvel,6.8,79,73.5,65058524.0,7.93,8.204101e+06,311591917
39,2010,Iron Man 2,Marvel,7.1,74,72.5,128122480.0,7.89,1.623859e+07,308745538
45,2012,Marvel's The Avengers,Marvel,8.7,92,89.5,207438708.0,7.92,2.619176e+07,314055984
37,2009,Watchmen,DC,7.7,64,70.5,55214334.0,7.50,7.361911e+06,307006550
24,2004,The Punisher,Marvel,6.4,29,46.5,13834527.0,6.21,2.227782e+06,293045739

In [78]:
# what are the Comic types?
sh['Comic'].unique()

array(['DC', 'Marvel'], dtype=object)

In [81]:
# How many movies?
len(sh)

49

In [83]:
# counts of each comic
sh['Comic'].value_counts()

Comic
Marvel    29
DC        20
Name: count, dtype: int64

In [85]:
sh.columns

Index(['Year', 'Title', 'Comic', 'IMDB Score', 'RT Score', 'Composite Score',
       'Opening Weekend  Box Office', 'Avg Ticket Price',
       'Opening Weekend Attendance', 'US Population That Year'],
      dtype='object')

In [86]:
sh.head()

,Year,Title,Comic,IMDB Score,RT Score,Composite Score,Opening Weekend Box Office,Avg Ticket Price,Opening Weekend Attendance,US Population That Year
0,1978,Superman,DC,7.3,95,84.0,7465343.0,2.34,3190317.521,222584545
1,1980,Superman II,DC,6.7,88,77.5,14100523.0,2.69,5241830.112,227224681
2,1982,Swamp Thing,DC,5.3,60,56.5,NaN,2.94,NaN,231664458
3,1983,Superman III,DC,4.9,24,36.5,13352357.0,3.15,4238843.492,233791994
4,1984,Supergirl,DC,4.2,8,25.0,5738249.0,3.36,1707812.202,235824902

In [89]:
# all titles with "Super" in them
sh [ sh['Title'].str.startswith("Super") ]

,Year,Title,Comic,IMDB Score,RT Score,Composite Score,Opening Weekend Box Office,Avg Ticket Price,Opening Weekend Attendance,US Population That Year
0,1978,Superman,DC,7.3,95,84.0,7465343.0,2.34,3190317.521,222584545
1,1980,Superman II,DC,6.7,88,77.5,14100523.0,2.69,5241830.112,227224681
3,1983,Superman III,DC,4.9,24,36.5,13352357.0,3.15,4238843.492,233791994
4,1984,Supergirl,DC,4.2,8,25.0,5738249.0,3.36,1707812.202,235824902
6,1987,Superman IV: The Quest for Peace,DC,3.6,10,23.0,5683122.0,3.91,1453483.887,242288918
28,2006,Superman Returns,DC,6.3,76,69.5,52535096.0,6.55,8020625.344,298593212

In [97]:
#title with highest RT score
maxrt = sh['RT Score'].max()
sh[ sh['RT Score'] == maxrt ]

,Year,Title,Comic,IMDB Score,RT Score,Composite Score,Opening Weekend Box Office,Avg Ticket Price,Opening Weekend Attendance,US Population That Year
0,1978,Superman,DC,7.3,95,84.0,7465343.0,2.34,3190317.521,222584545

In [ ]:
# Kaggle