# Code Samples From Large Group

Place your notes and code samples from large group here.

In [3]:
import pandas as pd
import numpy as np

In [4]:
df = pd.read_csv("reddit_news_articles.csv")

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 25 entries, 0 to 24
Data columns (total 51 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   kind                         25 non-null     object
 1   data.domain                  25 non-null     object
 2   data.banned_by               0 non-null      float64
 3   data.subreddit               25 non-null     object
 4   data.selftext_html           0 non-null      float64
 5   data.selftext                0 non-null      float64
 6   data.likes                   0 non-null      float64
 7   data.suggested_sort          0 non-null      float64
 8   data.user_reports            25 non-null     object
 9   data.secure_media            0 non-null      float64
 10  data.link_flair_text         0 non-null      float64
 11  data.id                      25 non-null     object
 12  data.from_kind               0 non-null      float64
 13  data.gilded                  25 non-null     int64
 14  data.archived                25 non-null     bool
 15  data.clicked                 25 non-null     bool
 16  data.report_reasons          0 non-null      float64
 17  data.author                  25 non-null     object
 18  data.media                   0 non-null      float64
 19  data.score                   25 non-null     int64
 20  data.approved_by             0 non-null      float64
 21  data.over_18                 25 non-null     bool
 22  data.hidden                  25 non-null     bool
 23  data.num_comments            25 non-null     int64
 24  data.thumbnail               0 non-null      float64
 25  data.subreddit_id            25 non-null     object
 26  data.hide_score              25 non-null     bool
 27  data.edited                  25 non-null     bool
 28  data.link_flair_css_class    0 non-null      float64
 29  data.author_flair_css_class  0 non-null      float64
 30  data.downs                   25 non-null     int64
 31  data.saved                   25 non-null     bool
 32  data.removal_reason          0 non-null      float64
 33  data.stickied                25 non-null     bool
 34  data.from                    0 non-null      float64
 35  data.is_self                 25 non-null     bool
 36  data.from_id                 0 non-null      float64
 37  data.permalink               25 non-null     object
 38  data.locked                  25 non-null     bool
 39  data.name                    25 non-null     object
 40  data.created                 25 non-null     float64
 41  data.url                     25 non-null     object
 42  data.author_flair_text       0 non-null      float64
 43  data.quarantine              25 non-null     bool
 44  data.title                   25 non-null     object
 45  data.created_utc             25 non-null     float64
 46  data.distinguished           0 non-null      float64
 47  data.mod_reports             25 non-null     object
 48  data.visited                 25 non-null     bool
 49  data.num_reports             0 non-null      float64
 50  data.ups                     25 non-null     int64
dtypes: bool(12), float64(22), int64(5), object(12)
memory usage: 8.0+ KB

In [6]:
df.describe()

,data.banned_by,data.selftext_html,data.selftext,data.likes,data.suggested_sort,data.secure_media,data.link_flair_text,data.from_kind,data.gilded,data.report_reasons,...,data.downs,data.removal_reason,data.from,data.from_id,data.created,data.author_flair_text,data.created_utc,data.distinguished,data.num_reports,data.ups
count,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,25.0,0.0,...,25.0,0.0,0.0,0.0,2.500000e+01,0.0,2.500000e+01,0.0,0.0,25.000000
mean,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,...,0.0,NaN,NaN,NaN,1.458733e+09,NaN,1.458704e+09,NaN,NaN,30.440000
std,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,...,0.0,NaN,NaN,NaN,3.688108e+04,NaN,3.688108e+04,NaN,NaN,74.512348
min,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,...,0.0,NaN,NaN,NaN,1.458655e+09,NaN,1.458627e+09,NaN,NaN,0.000000
25%,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,...,0.0,NaN,NaN,NaN,1.458700e+09,NaN,1.458671e+09,NaN,NaN,1.000000
50%,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,...,0.0,NaN,NaN,NaN,1.458727e+09,NaN,1.458698e+09,NaN,NaN,8.000000
75%,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,...,0.0,NaN,NaN,NaN,1.458767e+09,NaN,1.458738e+09,NaN,NaN,27.000000
max,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,...,0.0,NaN,NaN,NaN,1.458791e+09,NaN,1.458762e+09,NaN,NaN,376.000000

In [7]:
df.sample()

,kind,data.domain,data.banned_by,data.subreddit,data.selftext_html,data.selftext,data.likes,data.suggested_sort,data.user_reports,data.secure_media,...,data.url,data.author_flair_text,data.quarantine,data.title,data.created_utc,data.distinguished,data.mod_reports,data.visited,data.num_reports,data.ups
3,t3,sciencedaily.com,NaN,news,NaN,NaN,NaN,NaN,[],NaN,...,https://www.sciencedaily.com/releases/2016/03/...,NaN,False,Hubble Unveils Monster Stars,1.458698e+09,NaN,[],False,NaN,11

In [8]:
df['data.subreddit'].value_counts()

data.subreddit
news    25
Name: count, dtype: int64

In [9]:
df.sample()

,kind,data.domain,data.banned_by,data.subreddit,data.selftext_html,data.selftext,data.likes,data.suggested_sort,data.user_reports,data.secure_media,...,data.url,data.author_flair_text,data.quarantine,data.title,data.created_utc,data.distinguished,data.mod_reports,data.visited,data.num_reports,data.ups
21,t3,judicialwatch.org,NaN,news,NaN,NaN,NaN,NaN,[],NaN,...,http://www.judicialwatch.org/press-room/press-...,NaN,False,Judicial Watch: New Clinton Documents Raise Qu...,1.458660e+09,NaN,[],False,NaN,51

In [10]:
for index, row in df.iterrows():
    print(index, row['data.domain'], row['data.title'])

0 wdrb.com Man arrested for stealing SUV told police he needed it for job interview
1 cbc.ca Zika outbreak needs $4 million: WHO
2 foxnews.com Austin police to fire officer who shot, killed nude teen
3 sciencedaily.com Hubble Unveils Monster Stars
4 cbsnews.com ISIS application forms surface in intelligence haul on terror group's recruits
5 hosted.ap.org FDA Adds Boldest Warning To Most Widely Used Painkillers
6 cbsnews.com Brussels attacks expose gaping hole in airport security nets
7 baltimoresun.com Juveniles in Maryland's justice system are routinely strip-searched &amp; shackled: these practices apply to every youth...often for low-level offenses...also apply to juveniles who have not gone to court yet, and who could be found to have done nothing
8 news.sky.com Manhunt As Brussels Suspects Caught On CCTV: Two men who may be suicide bombers are wearing gloves that could have hidden detonators while a third man is being hunted.
9 time.com Possible MH370 Debris Discovered in South Africa
10 military.com Second ISIS Attack on New Marine Base Where Staff Sergeant Was Killed
11 theguardian.com Flashdrives for freedom? 20,000 USBs to be smuggled into North Korea
12 bigstory.ap.org Justices uphold $5.8 million award against Tyson Foods
13 theguardian.com The injunction is back: Well-known entertainer blocks extramarital affair story in the UK
14 fortune.com SpaceX Will Soon Launch Rockets Every Few Weeks
15 kristv.com 5 year old saves mom from drowning
16 reuters.com Kremlin says Syria peace talk participants must show patience, "always set to be long and difficult"
17 washingtonpost.com With presidents Obama, Castro watching, Rays beat Cuban team
18 abcnews.go.com Ex-Goldman Sachs Worker Gets No Prison Time in NY Theft Case
19 reuters.com Belgium identifies Brussels bomb suspect, suicide bombers
20 nbcnews.com Brussels Attacks: Suicide Bombers Were Brothers
21 judicialwatch.org Judicial Watch: New Clinton Documents Raise Questions on Benghazi, Clinton Foundation including undisclosed meetings with the Libyan President and President Clinton
22 militarytimes.com The U.S. military is moving into these 5 bases in the Philippines
23 techinsider.io Dutch prisons are closing because the country is so safe
24 freebeacon.com Obama annoyed at question about ISIS policy: “I’ve got a lot of things on my plate”

In [11]:
order_df = pd.read_json("orders.json")

In [19]:
order_df

,Customer,Items
0,"{'FirstName': 'Abby', 'LastName': 'Kuss'}","[{'Name': 'T-Shirt', 'Price': 10.0, 'Quantity'..."
1,"{'FirstName': 'Bette', 'LastName': 'Alott'}","[{'Name': 'Shoes', 'Price': 25.0, 'Quantity': ..."
2,"{'FirstName': 'Chris', 'LastName': 'Peanugget'}","[{'Name': 'T-Shirt', 'Price': 10.0, 'Quantity'..."

In [20]:
# Get me a first name
order_df.loc[1,'Customer']['FirstName']

'Bette'

In [23]:
#Get me some shoes!
order_df.loc[1,'Items'][0]['Name']

'Shoes'

In [27]:
# Load in the list/dict
import json
with open("orders.json", "r") as f:
    data = json.load(f)
data

[{'Customer': {'FirstName': 'Abby', 'LastName': 'Kuss'},
  'Items': [{'Name': 'T-Shirt', 'Price': 10.0, 'Quantity': 3},
   {'Name': 'Jacket', 'Price': 20.0, 'Quantity': 1}]},
 {'Customer': {'FirstName': 'Bette', 'LastName': 'Alott'},
  'Items': [{'Name': 'Shoes', 'Price': 25.0, 'Quantity': 1},
   {'Name': 'Jacket', 'Price': 20.0, 'Quantity': 1}]},
 {'Customer': {'FirstName': 'Chris', 'LastName': 'Peanugget'},
  'Items': [{'Name': 'T-Shirt', 'Price': 10.0, 'Quantity': 1}]}]

In [28]:
# JSON Normalize breaks up the dictionary
orders_df = pd.json_normalize(data)
orders_df

,Items,Customer.FirstName,Customer.LastName
0,"[{'Name': 'T-Shirt', 'Price': 10.0, 'Quantity'...",Abby,Kuss
1,"[{'Name': 'Shoes', 'Price': 25.0, 'Quantity': ...",Bette,Alott
2,"[{'Name': 'T-Shirt', 'Price': 10.0, 'Quantity'...",Chris,Peanugget

In [29]:
orders_df.loc[1,'Customer.LastName']

'Alott'

In [30]:
# normalize on the list
orders_df = pd.json_normalize(data, record_path='Items')
orders_df

      Name  Price  Quantity
0  T-Shirt   10.0         3
1   Jacket   20.0         1
2    Shoes   25.0         1
3   Jacket   20.0         1
4  T-Shirt   10.0         1

In [35]:
orders_df = pd.json_normalize(data, record_path='Items', 
                              meta = [ 
                                  ["Customer", "FirstName"],
                                  ["Customer", "LastName"]
                              ] )
orders_df

      Name  Price  Quantity Customer.FirstName Customer.LastName
0  T-Shirt   10.0         3               Abby              Kuss
1   Jacket   20.0         1               Abby              Kuss
2    Shoes   25.0         1              Bette             Alott
3   Jacket   20.0         1              Bette             Alott
4  T-Shirt   10.0         1              Chris         Peanugget

In [32]:
x = [ 
  {"a" : {"b": 1, "x": 0}, "c" : [10,11]},
  {"a" : {"b": 2, "x": 0}, "c" : [21,22,23]}
]

In [33]:
y = pd.json_normalize(x)

In [34]:
y

              c  a.b  a.x
0      [10, 11]    1    0
1  [21, 22, 23]    2    0

In [35]:
y = pd.json_normalize(x, record_path="c")

In [36]:
y

    0
0  10
1  11
2  21
3  22
4  23

In [ ]:
# error!!!!!
tables = pd.read_html("http://ist256.github.io/")

In [44]:
headers = {"User-Agent": "Mozilla/5.0"}  # <== This reports you as a web browser
tables = pd.read_html("http://ist256.github.io/", storage_options=headers)
# list of tables on the page...each is a dataframe.
tables

[          Dates                                              Topic
 0   1/12 - 1/18      Lesson 01: Introduction to Python Programming
 1   1/21 - 1/25  Lesson 02: Input, Output, Variables and Types ...
 2    1/26 - 2/1                            Lesson 03: Conditionals
 3     2/2 - 2/8                              Lesson 04: Iterations
 4    2/9 - 2/15         Lesson 05: User-defined Functions, Modules
 5   2/16 - 2/22             Lesson 06: Strings and Text Processing
 6    2/23 - 3/2                Lesson 07: File I/O and Persistence
 7     3/2 - 3/8                 Exam Week E1 on 3/2 in Large Group
 8    3/9 - 3/15                            SPRING BREAK No Classes
 9   3/16 - 3/22                                   Lesson 08: Lists
 10  3/23 - 3/29                   Lesson 09: Dictionaries and JSON
 11   3/30 - 4/5                                Lesson 10: Pandas I
 12   4/6 - 4/12  Lesson 11: Pandas II  P1 project deliverable d...
 13  4/13 - 4/19                      Lesson 12: Data Visualization
 14  4/20 - 4/26  Lesson 13: Web API’s P2 project deliverable du...
 15   4/27 - 5/4  E2 on 4/27 in Large Group  P3 and P4 Project d...,
      Date Due  Time Due Gradebook  Points       Where?  \
 0   1/16/2026  11:59 PM       L01       3   Jupyterhub
 1   1/14/2026  11:59 PM        C1       3  Small Group
 2   1/20/2026  11:59 PM       L02       3   Jupyterhub
 3   1/21/2026  11:59 PM       S02       3   Jupyterhub
 4   1/23/2026  11:59 PM       H02       3   Jupyterhub
 5   1/27/2026  11:59 PM       L03       3   Jupyterhub
 6   1/28/2026  11:59 PM       S03       3   Jupyterhub
 7   1/30/2026  11:59 PM       H03       3   Jupyterhub
 8    2/3/2026  11:59 PM       L04       3   Jupyterhub
 9    2/4/2026  11:59 PM       S04       3   Jupyterhub
 10   2/6/2026  11:59 PM       H04       3   Jupyterhub
 11  2/10/2026  11:59 PM       L05       3   Jupyterhub
 12  2/11/2026  11:59 PM       S05       3   Jupyterhub
 13  2/13/2026  11:59 PM       H05       3   Jupyterhub
 14  2/17/2026  11:59 PM       L06       3   Jupyterhub
 15  2/18/2026  11:59 PM       S06       3   Jupyterhub
 16  2/20/2026  11:59 PM       H06       3   Jupyterhub
 17  2/24/2026  11:59 PM       L07       3   Jupyterhub
 18  2/25/2026  11:59 PM       S07       3   Jupyterhub
 19  2/27/2026  11:59 PM       H07       3   Jupyterhub
 20   3/3/2026  11:59 PM        E1      45  Large Group
 21   3/5/2026  11:59 PM        C2       3  Small Group
 22  3/17/2026  11:59 PM       L08       3   Jupyterhub
 23  3/18/2026  11:59 PM       S08       3   Jupyterhub
 24  3/20/2026  11:59 PM       H08       3   Jupyterhub
 25  3/24/2026  11:59 PM       L09       3   Jupyterhub
 26  3/25/2026  11:59 PM       S09       3   Jupyterhub
 27  3/27/2026  11:59 PM       H09       3   Jupyterhub
 28  3/31/2026  11:59 PM       L10       3   Jupyterhub
 29   4/1/2026  11:59 PM       S10       3   Jupyterhub
 30   4/3/2026  11:59 PM       H10       3   Jupyterhub
 31   4/7/2026  11:59 PM       L11       3   Jupyterhub
 32   4/8/2026  11:59 PM       S11       3   Jupyterhub
 33  4/10/2026  11:59 PM       H11       3   Jupyterhub
 34  4/10/2026  11:59 PM        P1       0   Jupyterhub
 35  4/14/2026  11:59 PM       L12       3   Jupyterhub
 36  4/15/2026  11:59 PM       S12       3   Jupyterhub
 37  4/17/2026  11:59 PM       H12       3   Jupyterhub
 38  4/21/2026  11:59 PM       L13       3   Jupyterhub
 39  4/22/2026  11:59 PM       S13       3   Jupyterhub
 40  4/24/2026  11:59 PM       H13       3   Jupyterhub
 41  4/24/2026  11:59 PM        P2       0   Jupyterhub
 42  4/28/2026  11:59 PM        E2      45  Large Group
 43   5/4/2026  11:59 PM        P3       0   Jupyterhub
 44   5/4/2026  11:59 PM        P4      49   Jupyterhub

                                        What is Due?
 0                          01-Intro/LAB-Intro.ipynb
 1                               Course Diagnostic 1
 2                  02-Variables/LAB-Variables.ipynb
 3           02-Variables/SmallGroup-Variables.ipynb
 4                   02-Variables/HW-Variables.ipynb
 5            03-Conditionals/LAB-Conditionals.ipynb
 6     03-Conditionals/SmallGroup-Conditionals.ipynb
 7             03-Conditionals/HW-Conditionals.ipynb
 8                04-Iterations/LAB-Iterations.ipynb
 9         04-Iterations/SmallGroup-Iterations.ipynb
 10                04-Iterations/HW-Iterations.ipynb
 11                 05-Functions/LAB-Functions.ipynb
 12          05-Functions/SmallGroup-Functions.ipynb
 13                  05-Functions/HW-Functions.ipynb
 14                     06-Strings/LAB-Strings.ipynb
 15              06-Strings/SmallGroup-Strings.ipynb
 16                      06-Strings/HW-Strings.ipynb
 17                         07-Files/LAB-Files.ipynb
 18                  07-Files/SmallGroup-Files.ipynb
 19                          07-Files/HW-Files.ipynb
 20                E1: Exam 1 (Focus on Lessons 1-7)
 21                              Course Diagnostic 2
 22                         08-Lists/LAB-Lists.ipynb
 23                  08-Lists/SmallGroup-Lists.ipynb
 24                          08-Lists/HW-Lists.ipynb
 25           09-Dictionaries/LAB-Dictionaries.ipynb
 26    09-Dictionaries/SmallGroup-Dictionaries.ipynb
 27            09-Dictionaries/HW-Dictionaries.ipynb
 28                    10-Pandas-I/LAB-PandasI.ipynb
 29             10-Pandas-I/SmallGroup-PandasI.ipynb
 30                     10-Pandas-I/HW-PandasI.ipynb
 31                  11-Pandas-II/LAB-PandasII.ipynb
 32           11-Pandas-II/SmallGroup-PandasII.ipynb
 33                   11-Pandas-II/HW-PandasII.ipynb
 34                                 project/P1.ipynb
 35         12-Visualization/LAB-Visualization.ipynb
 36  12-Visualization/SmallGroup-Visualization.ipynb
 37          12-Visualization/HW-Visualization.ipynb
 38                     13-WebAPIs/LAB-Webapis.ipynb
 39              13-WebAPIs/SmallGroup-Webapis.ipynb
 40                      13-WebAPIs/HW-Webapis.ipynb
 41                                 project/P2.ipynb
 42               E2: Exam 2 (Focus on Lessons 8-13)
 43                                 project/P3.ipynb
 44                                 project/P4.ipynb  ]

In [46]:
#looping over a dataframe
for i, row in tables[1].iterrows():
    print(row['Gradebook'])

L01
C1
L02
S02
H02
L03
S03
H03
L04
S04
H04
L05
S05
H05
L06
S06
H06
L07
S07
H07
E1
C2
L08
S08
H08
L09
S09
H09
L10
S10
H10
L11
S11
H11
P1
L12
S12
H12
L13
S13
H13
P2
E2
P3
P4

In [40]:
headers = {"User-Agent": "Mozilla/5.0"}
tables = pd.read_html("https://www.baseball-reference.com/leagues/MLB-standings.shtml", storage_options=headers)
len(tables)

6

In [41]:
al_east = tables[0]

In [42]:
al_east

                  Tm  W  L   W-L%   GB
0   New York Yankees  8  2  0.800   --
1     Boston Red Sox  7  3  0.700  1.0
2  Baltimore Orioles  5  4  0.556  2.5
3     Tampa Bay Rays  5  5  0.500  3.0
4  Toronto Blue Jays  4  6  0.400  4.0

In [45]:
al_east['GP'] = al_east['W'] + al_east['L']

In [46]:
al_east

                  Tm  W  L   W-L%   GB  GP
0   New York Yankees  8  2  0.800   --  10
1     Boston Red Sox  7  3  0.700  1.0  10
2  Baltimore Orioles  5  4  0.556  2.5   9
3     Tampa Bay Rays  5  5  0.500  3.0  10
4  Toronto Blue Jays  4  6  0.400  4.0  10

In [47]:
def add(wins, losses):
    return wins + losses

assert add(1,1) == 2

In [48]:
al_east['GP'] = al_east.apply(lambda row: add(row['W'], row['L']), axis=1)

In [49]:
al_east

                  Tm  W  L   W-L%   GB  GP
0   New York Yankees  8  2  0.800   --  10
1     Boston Red Sox  7  3  0.700  1.0  10
2  Baltimore Orioles  5  4  0.556  2.5   9
3     Tampa Bay Rays  5  5  0.500  3.0  10
4  Toronto Blue Jays  4  6  0.400  4.0  10