# Code Samples From Large Group

Place your notes and code samples from large group here.

In [1]:
import pandas as pd
import numpy as np

In [2]:
orders = pd.read_json("orders.json")

In [3]:
orders

,Customer,Items
0,"{'FirstName': 'Abby', 'LastName': 'Kuss'}","[{'Name': 'T-Shirt', 'Price': 10.0, 'Quantity'..."
1,"{'FirstName': 'Bette', 'LastName': 'Alott'}","[{'Name': 'Shoes', 'Price': 25.0, 'Quantity': ..."
2,"{'FirstName': 'Chris', 'LastName': 'Peanugget'}","[{'Name': 'T-Shirt', 'Price': 10.0, 'Quantity'..."

In [11]:
# Retrieves Customer 1 first name
orders.loc[1, "Customer"]['FirstName']

'Bette'

In [15]:
orders.loc[1, "Items"]

[{'Name': 'Shoes', 'Price': 25.0, 'Quantity': 1},
 {'Name': 'Jacket', 'Price': 20.0, 'Quantity': 1}]

In [14]:
# Shoes
orders.loc[1, "Items"][0]['Price']

25.0

In [16]:
airports = pd.read_json("airports.json")
airports.head()

,ident,type,name,geo,code
0,03N,small_airport,Utirik Airport,"{'lat': '11.222', 'lon': '169.852005', 'ft_ele...","{'gps': 'K03N', 'iata': 'UTK', 'local': '03N'}"
1,07FA,small_airport,Ocean Reef Club Airport,"{'lat': '25.325399398804', 'lon': '-80.2748031...","{'gps': '07FA', 'iata': 'OCA', 'local': '07FA'}"
2,0AK,small_airport,Pilot Station Airport,"{'lat': '61.934601', 'lon': '-162.899994', 'ft...","{'iata': 'PQS', 'local': '0AK'}"
3,0CO2,small_airport,Crested Butte Airpark,"{'lat': '38.851918', 'lon': '-106.928341', 'ft...","{'gps': '0CO2', 'iata': 'CSE', 'local': '0CO2'}"
4,0TE7,small_airport,LBJ Ranch Airport,"{'lat': '30.251801', 'lon': '-98.622498', 'ft_...","{'gps': '0TE7', 'iata': 'JCY', 'local': '0TE7'}"

In [18]:
import json
with open ("orders.json","r") as f:
    orders = json.load(f)

orders

[{'Customer': {'FirstName': 'Abby', 'LastName': 'Kuss'},
  'Items': [{'Name': 'T-Shirt', 'Price': 10.0, 'Quantity': 3},
   {'Name': 'Jacket', 'Price': 20.0, 'Quantity': 1}]},
 {'Customer': {'FirstName': 'Bette', 'LastName': 'Alott'},
  'Items': [{'Name': 'Shoes', 'Price': 25.0, 'Quantity': 1},
   {'Name': 'Jacket', 'Price': 20.0, 'Quantity': 1}]},
 {'Customer': {'FirstName': 'Chris', 'LastName': 'Peanugget'},
  'Items': [{'Name': 'T-Shirt', 'Price': 10.0, 'Quantity': 1}]}]

In [20]:
# splits out the dictionary parts into columns
order_df = pd.json_normalize(orders)
order_df

,Items,Customer.FirstName,Customer.LastName
0,"[{'Name': 'T-Shirt', 'Price': 10.0, 'Quantity'...",Abby,Kuss
1,"[{'Name': 'Shoes', 'Price': 25.0, 'Quantity': ...",Bette,Alott
2,"[{'Name': 'T-Shirt', 'Price': 10.0, 'Quantity'...",Chris,Peanugget

In [22]:
orders_df = pd.json_normalize(orders, record_path="Items")
orders_df

      Name  Price  Quantity
0  T-Shirt   10.0         3
1   Jacket   20.0         1
2    Shoes   25.0         1
3   Jacket   20.0         1
4  T-Shirt   10.0         1

In [27]:
orders_df = pd.json_normalize(orders, record_path="Items", meta=[
    ["Customer", "FirstName" ], 
    ["Customer", "LastName" ]])
orders_df

      Name  Price  Quantity Customer.FirstName Customer.LastName
0  T-Shirt   10.0         3               Abby              Kuss
1   Jacket   20.0         1               Abby              Kuss
2    Shoes   25.0         1              Bette             Alott
3   Jacket   20.0         1              Bette             Alott
4  T-Shirt   10.0         1              Chris         Peanugget

In [28]:
orders

[{'Customer': {'FirstName': 'Abby', 'LastName': 'Kuss'},
  'Items': [{'Name': 'T-Shirt', 'Price': 10.0, 'Quantity': 3},
   {'Name': 'Jacket', 'Price': 20.0, 'Quantity': 1}]},
 {'Customer': {'FirstName': 'Bette', 'LastName': 'Alott'},
  'Items': [{'Name': 'Shoes', 'Price': 25.0, 'Quantity': 1},
   {'Name': 'Jacket', 'Price': 20.0, 'Quantity': 1}]},
 {'Customer': {'FirstName': 'Chris', 'LastName': 'Peanugget'},
  'Items': [{'Name': 'T-Shirt', 'Price': 10.0, 'Quantity': 1}]}]

In [29]:
orders1 = pd.read_json("orders.json")
orders1

,Customer,Items
0,"{'FirstName': 'Abby', 'LastName': 'Kuss'}","[{'Name': 'T-Shirt', 'Price': 10.0, 'Quantity'..."
1,"{'FirstName': 'Bette', 'LastName': 'Alott'}","[{'Name': 'Shoes', 'Price': 25.0, 'Quantity': ..."
2,"{'FirstName': 'Chris', 'LastName': 'Peanugget'}","[{'Name': 'T-Shirt', 'Price': 10.0, 'Quantity'..."

In [30]:
orders_df

      Name  Price  Quantity Customer.FirstName Customer.LastName
0  T-Shirt   10.0         3               Abby              Kuss
1   Jacket   20.0         1               Abby              Kuss
2    Shoes   25.0         1              Bette             Alott
3   Jacket   20.0         1              Bette             Alott
4  T-Shirt   10.0         1              Chris         Peanugget

In [33]:
# this gets you the most ordered item by customer
orders_df[ orders_df["Quantity"] == orders_df["Quantity"].max()]

      Name  Price  Quantity Customer.FirstName Customer.LastName
0  T-Shirt   10.0         3               Abby              Kuss

In [40]:
# same but with other dataframe
max = 0
for i, row in orders1.iterrows():
    for item in row["Items"]:
        if item["Quantity"] > max:
            max = item["Quantity"]
print(max)

3

In [45]:
x = [ 
  {"a" : {"b": 1, "w" : "Yes"}, "c" : [10,11]},
  {"a" : {"b": 2, "w" : "No" }, "c" : [21,22,23]}
]
df = pd.json_normalize(x)
df

              c  a.b  a.w
0      [10, 11]    1  Yes
1  [21, 22, 23]    2   No

In [46]:
df2 = pd.json_normalize(x, record_path="c")
df2

    0
0  10
1  11
2  21
3  22
4  23

In [48]:
df2 = pd.json_normalize(x, record_path="c", meta = [
    ["a","b"],
    ["a","w"]
])
df2

    0 a.b  a.w
0  10   1  Yes
1  11   1  Yes
2  21   2   No
3  22   2   No
4  23   2   No

In [50]:
# Here are all the nos
df2[ df2["a.w"] == "No" ]

    0 a.b a.w
2  21   2  No
3  22   2  No
4  23   2  No

In [53]:
df2.to_csv("mydata.csv", index=False)

In [54]:
mydata = pd.read_csv("mydata.csv")
mydata

    0  a.b  a.w
0  10    1  Yes
1  11    1  Yes
2  21    2   No
3  22    2   No
4  23    2   No

In [56]:
website = "https://www.baseball-reference.com/leagues/MLB-standings.shtml"
dataframes = pd.read_html(website)

In [57]:
type(dataframes)

list

In [58]:
type(dataframes[0])

pandas.core.frame.DataFrame

In [61]:
dataframes[0]["Div"] ="AL East"

In [62]:
dataframes[1]["Div"] = "AL Cent"

In [63]:
dataframes[1]

                    Tm  W  L   W-L%   GB      Div
0  Cleveland Guardians  6  4  0.600   --  AL Cent
1    Chicago White Sox  4  5  0.444  1.5  AL Cent
2       Detroit Tigers  4  5  0.444  1.5  AL Cent
3   Kansas City Royals  4  5  0.444  1.5  AL Cent
4      Minnesota Twins  3  6  0.333  2.5  AL Cent

In [64]:
divisions = [ "AL East", "AL Cent", "AL West", "NL East", "NL Cent", "NL West"]

In [66]:
for i in range(len(divisions)):
    dataframes[i]["Div"] = divisions[i]

In [67]:
dataframes[4]

                    Tm  W  L   W-L%   GB      Div
0    Milwaukee Brewers  7  2  0.778   --  NL Cent
1      Cincinnati Reds  6  3  0.667  1.0  NL Cent
2   Pittsburgh Pirates  6  3  0.667  1.0  NL Cent
3  St. Louis Cardinals  5  4  0.556  2.0  NL Cent
4         Chicago Cubs  4  5  0.444  3.0  NL Cent

In [68]:
dataframes[5]

                     Tm  W  L   W-L%   GB      Div
0   Los Angeles Dodgers  7  2  0.778   --  NL West
1  Arizona Diamondbacks  5  5  0.500  2.5  NL West
2      San Diego Padres  4  5  0.444  3.0  NL West
3      Colorado Rockies  3  6  0.333  4.0  NL West
4  San Francisco Giants  3  7  0.300  4.5  NL West

In [70]:
mlb = pd.concat(dataframes[0:6])
mlb

                      Tm  W  L   W-L%   GB      Div
0       New York Yankees  7  2  0.778   --  AL East
1         Tampa Bay Rays  4  5  0.444  3.0  AL East
2      Toronto Blue Jays  4  5  0.444  3.0  AL East
3      Baltimore Orioles  3  6  0.333  4.0  AL East
4         Boston Red Sox  2  7  0.222  5.0  AL East
0    Cleveland Guardians  6  4  0.600   --  AL Cent
1      Chicago White Sox  4  5  0.444  1.5  AL Cent
2         Detroit Tigers  4  5  0.444  1.5  AL Cent
3     Kansas City Royals  4  5  0.444  1.5  AL Cent
4        Minnesota Twins  3  6  0.333  2.5  AL Cent
0         Houston Astros  6  4  0.600   --  AL West
1     Los Angeles Angels  5  5  0.500  1.0  AL West
2          Texas Rangers  4  5  0.444  1.5  AL West
3       Seattle Mariners  4  6  0.400  2.0  AL West
4              Athletics  3  6  0.333  2.5  AL West
0          Miami Marlins  6  3  0.667   --  NL East
1         Atlanta Braves  6  4  0.600  0.5  NL East
2          New York Mets  6  4  0.600  0.5  NL East
3  Philadelphia Phillies  5  4  0.556  1.0  NL East
4   Washington Nationals  3  6  0.333  3.0  NL East
0      Milwaukee Brewers  7  2  0.778   --  NL Cent
1        Cincinnati Reds  6  3  0.667  1.0  NL Cent
2     Pittsburgh Pirates  6  3  0.667  1.0  NL Cent
3    St. Louis Cardinals  5  4  0.556  2.0  NL Cent
4           Chicago Cubs  4  5  0.444  3.0  NL Cent
0    Los Angeles Dodgers  7  2  0.778   --  NL West
1   Arizona Diamondbacks  5  5  0.500  2.5  NL West
2       San Diego Padres  4  5  0.444  3.0  NL West
3       Colorado Rockies  3  6  0.333  4.0  NL West
4   San Francisco Giants  3  7  0.300  4.5  NL West

In [72]:
def games_played(wins: int, losses: int) -> int:
    '''
    this silly function takes two numbers wins and losses 
    and adds em up and returns them
    '''
    total = wins + losses
    return total

print(games_played(7,3) == 10)

True

In [73]:
mlb["GP"] = mlb.apply( lambda row: games_played(row["W"], row["L"]), axis=1)
mlb

                      Tm  W  L   W-L%   GB      Div  GP
0       New York Yankees  7  2  0.778   --  AL East   9
1         Tampa Bay Rays  4  5  0.444  3.0  AL East   9
2      Toronto Blue Jays  4  5  0.444  3.0  AL East   9
3      Baltimore Orioles  3  6  0.333  4.0  AL East   9
4         Boston Red Sox  2  7  0.222  5.0  AL East   9
0    Cleveland Guardians  6  4  0.600   --  AL Cent  10
1      Chicago White Sox  4  5  0.444  1.5  AL Cent   9
2         Detroit Tigers  4  5  0.444  1.5  AL Cent   9
3     Kansas City Royals  4  5  0.444  1.5  AL Cent   9
4        Minnesota Twins  3  6  0.333  2.5  AL Cent   9
0         Houston Astros  6  4  0.600   --  AL West  10
1     Los Angeles Angels  5  5  0.500  1.0  AL West  10
2          Texas Rangers  4  5  0.444  1.5  AL West   9
3       Seattle Mariners  4  6  0.400  2.0  AL West  10
4              Athletics  3  6  0.333  2.5  AL West   9
0          Miami Marlins  6  3  0.667   --  NL East   9
1         Atlanta Braves  6  4  0.600  0.5  NL East  10
2          New York Mets  6  4  0.600  0.5  NL East  10
3  Philadelphia Phillies  5  4  0.556  1.0  NL East   9
4   Washington Nationals  3  6  0.333  3.0  NL East   9
0      Milwaukee Brewers  7  2  0.778   --  NL Cent   9
1        Cincinnati Reds  6  3  0.667  1.0  NL Cent   9
2     Pittsburgh Pirates  6  3  0.667  1.0  NL Cent   9
3    St. Louis Cardinals  5  4  0.556  2.0  NL Cent   9
4           Chicago Cubs  4  5  0.444  3.0  NL Cent   9
0    Los Angeles Dodgers  7  2  0.778   --  NL West   9
1   Arizona Diamondbacks  5  5  0.500  2.5  NL West  10
2       San Diego Padres  4  5  0.444  3.0  NL West   9
3       Colorado Rockies  3  6  0.333  4.0  NL West   9
4   San Francisco Giants  3  7  0.300  4.5  NL West  10

In [74]:
mlb.to_csv("mlb.csv", index=False)

In [76]:
mlb = pd.read_csv("mlb.csv")
mlb.sample(5)

                       Tm  W  L   W-L%   GB      Div  GP
22     Pittsburgh Pirates  6  3  0.667  1.0  NL Cent   9
29   San Francisco Giants  3  7  0.300  4.5  NL West  10
25    Los Angeles Dodgers  7  2  0.778   --  NL West   9
18  Philadelphia Phillies  5  4  0.556  1.0  NL East   9
4          Boston Red Sox  2  7  0.222  5.0  AL East   9

In [83]:
# When you get an HTTP Error, put in a user agent
# string "Mozilla/5.0 
website= "http://ist256.github.io/"
user_agent= { "User-Agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 14_0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/141.0.7390.108 Safari/537.36" }
tables = pd.read_html(website, storage_options = user_agent)

In [84]:
tables[1]

,Date Due,Time Due,Gradebook,Points,Where?,What is Due?
0,1/16/2026,11:59 PM,L01,3,Jupyterhub,01-Intro/LAB-Intro.ipynb
1,1/14/2026,11:59 PM,C1,3,Small Group,Course Diagnostic 1
2,1/20/2026,11:59 PM,L02,3,Jupyterhub,02-Variables/LAB-Variables.ipynb
3,1/21/2026,11:59 PM,S02,3,Jupyterhub,02-Variables/SmallGroup-Variables.ipynb
4,1/23/2026,11:59 PM,H02,3,Jupyterhub,02-Variables/HW-Variables.ipynb
5,1/27/2026,11:59 PM,L03,3,Jupyterhub,03-Conditionals/LAB-Conditionals.ipynb
6,1/28/2026,11:59 PM,S03,3,Jupyterhub,03-Conditionals/SmallGroup-Conditionals.ipynb
7,1/30/2026,11:59 PM,H03,3,Jupyterhub,03-Conditionals/HW-Conditionals.ipynb
8,2/3/2026,11:59 PM,L04,3,Jupyterhub,04-Iterations/LAB-Iterations.ipynb
9,2/4/2026,11:59 PM,S04,3,Jupyterhub,04-Iterations/SmallGroup-Iterations.ipynb
10,2/6/2026,11:59 PM,H04,3,Jupyterhub,04-Iterations/HW-Iterations.ipynb
11,2/10/2026,11:59 PM,L05,3,Jupyterhub,05-Functions/LAB-Functions.ipynb
12,2/11/2026,11:59 PM,S05,3,Jupyterhub,05-Functions/SmallGroup-Functions.ipynb
13,2/13/2026,11:59 PM,H05,3,Jupyterhub,05-Functions/HW-Functions.ipynb
14,2/17/2026,11:59 PM,L06,3,Jupyterhub,06-Strings/LAB-Strings.ipynb
15,2/18/2026,11:59 PM,S06,3,Jupyterhub,06-Strings/SmallGroup-Strings.ipynb
16,2/20/2026,11:59 PM,H06,3,Jupyterhub,06-Strings/HW-Strings.ipynb
17,2/24/2026,11:59 PM,L07,3,Jupyterhub,07-Files/LAB-Files.ipynb
18,2/25/2026,11:59 PM,S07,3,Jupyterhub,07-Files/SmallGroup-Files.ipynb
19,2/27/2026,11:59 PM,H07,3,Jupyterhub,07-Files/HW-Files.ipynb
20,3/3/2026,11:59 PM,E1,45,Large Group,E1: Exam 1 (Focus on Lessons 1-7)
21,3/5/2026,11:59 PM,C2,3,Small Group,Course Diagnostic 2
22,3/17/2026,11:59 PM,L08,3,Jupyterhub,08-Lists/LAB-Lists.ipynb
23,3/18/2026,11:59 PM,S08,3,Jupyterhub,08-Lists/SmallGroup-Lists.ipynb
24,3/20/2026,11:59 PM,H08,3,Jupyterhub,08-Lists/HW-Lists.ipynb
25,3/24/2026,11:59 PM,L09,3,Jupyterhub,09-Dictionaries/LAB-Dictionaries.ipynb
26,3/25/2026,11:59 PM,S09,3,Jupyterhub,09-Dictionaries/SmallGroup-Dictionaries.ipynb
27,3/27/2026,11:59 PM,H09,3,Jupyterhub,09-Dictionaries/HW-Dictionaries.ipynb
28,3/31/2026,11:59 PM,L10,3,Jupyterhub,10-Pandas-I/LAB-PandasI.ipynb
29,4/1/2026,11:59 PM,S10,3,Jupyterhub,10-Pandas-I/SmallGroup-PandasI.ipynb
30,4/3/2026,11:59 PM,H10,3,Jupyterhub,10-Pandas-I/HW-PandasI.ipynb
31,4/7/2026,11:59 PM,L11,3,Jupyterhub,11-Pandas-II/LAB-PandasII.ipynb
32,4/8/2026,11:59 PM,S11,3,Jupyterhub,11-Pandas-II/SmallGroup-PandasII.ipynb
33,4/10/2026,11:59 PM,H11,3,Jupyterhub,11-Pandas-II/HW-PandasII.ipynb
34,4/10/2026,11:59 PM,P1,0,Jupyterhub,project/P1.ipynb
35,4/14/2026,11:59 PM,L12,3,Jupyterhub,12-Visualization/LAB-Visualization.ipynb
36,4/15/2026,11:59 PM,S12,3,Jupyterhub,12-Visualization/SmallGroup-Visualization.ipynb
37,4/17/2026,11:59 PM,H12,3,Jupyterhub,12-Visualization/HW-Visualization.ipynb
38,4/21/2026,11:59 PM,L13,3,Jupyterhub,13-WebAPIs/LAB-Webapis.ipynb
39,4/22/2026,11:59 PM,S13,3,Jupyterhub,13-WebAPIs/SmallGroup-Webapis.ipynb
40,4/24/2026,11:59 PM,H13,3,Jupyterhub,13-WebAPIs/HW-Webapis.ipynb
41,4/24/2026,11:59 PM,P2,0,Jupyterhub,project/P2.ipynb
42,4/28/2026,11:59 PM,E2,45,Large Group,E2: Exam 2 (Focus on Lessons 8-13)
43,5/4/2026,11:59 PM,P3,0,Jupyterhub,project/P3.ipynb
44,5/4/2026,11:59 PM,P4,49,Jupyterhub,project/P4.ipynb